# Numpy

- provides more functionality to work with multi dimensional arrays
- much more convenient in terms of helper functions as well as syntax

In [0]:
import numpy as np

The simplest way to get started with Numpy is to create an array. This can be done by invoking the array method in numpy and passing it an argument. This may be a list or a tuple or a set

In [0]:
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [0]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [0]:
np.array(set([1,2,3,4]))

array({1, 2, 3, 4}, dtype=object)

In [0]:
set([1,2,3, 4, 4])

{1, 2, 3, 4}

To create an array from 0 to n-1 we use the range function in normal python

In [1]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

However in numpy we use the `np.arange` function

In [0]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])